# Generated by Django 6.0.4 on 2026-04-11 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension, BtreeGinExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # PostgreSQL extensions
        CreateExtension('pgcrypto'),
        CreateExtension('pg_trgm'),

        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('location', models.TextField()),
                ('plus_one_allowed', models.BooleanField(default=False)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('waitlist', 'Waitlist')], default='yes', max_length=10)),
                ('plus_one_name', models.TextField(blank=True, null=True)),
                ('dietary_preferences', models.TextField(blank=True, null=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='rsvp_app.event')),
            ],
            options={
                'db_table': 'rsvp',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='uq_rsvp_email_per_event')],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dietary_preferences', models.TextField(blank=True, null=True)),
                ('plus_one_name', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='rsvp_app.event')),
            ],
            options={
                'db_table': 'waitlist_entry',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='uq_waitlist_email_per_event'), models.UniqueConstraint(fields=('event', 'position'), name='uq_waitlist_position')],
            },
        ),

        # updated_at trigger function + indexes
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION set_updated_at()
                RETURNS TRIGGER AS $$
                BEGIN
                    NEW.updated_at = NOW();
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER trg_event_updated_at
                    BEFORE UPDATE ON event
                    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

                CREATE TRIGGER trg_rsvp_updated_at
                    BEFORE UPDATE ON rsvp
                    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

                CREATE TRIGGER trg_waitlist_updated_at
                    BEFORE UPDATE ON waitlist_entry
                    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

                CREATE INDEX idx_rsvp_name_trgm ON rsvp USING gin (name gin_trgm_ops);
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_event_updated_at ON event;
                DROP TRIGGER IF EXISTS trg_rsvp_updated_at ON rsvp;
                DROP TRIGGER IF EXISTS trg_waitlist_updated_at ON waitlist_entry;
                DROP FUNCTION IF EXISTS set_updated_at();
                DROP INDEX IF EXISTS idx_rsvp_name_trgm;
            """,
        ),
    ]
